// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxiuucskvfldllmdwxqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4aXV1Y3NrdmZsZGxsbWR3eHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTQzMDMsImV4cCI6MjA1ODIzMDMwM30.EypwT6R1Ln6tZ3736bEIWh_8SqQABqX3TtZbHGpCCh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);